### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by theacodes**
This library is wonderful, however, it's missing an explicit license in its source code. This adds the text of the MIT license along with the name of the original author. This helps folks like me make sure we follow the license terms when using this library. :)

### CODE REVIEW

**Comment by PetteriAimonen** [comment]
That license file is not correct. Most of libfixmath is written by someone else, you'd need to dig to either commit history or the Google Code archive to check details. I just cloned it here when Google Code was going down.

**Comment by theacodes** [comment]
Cool, I'll do some digging and update it. :)

**Comment by PetteriAimonen** [comment]
Thanks :)

**Comment by theacodes** [comment]
Done, let me know what you think.

**Comment by PetteriAimonen** [comment]
Looks good, thanks!

**Pull request merged**
